CREATE TABLE deck (
    card VARCHAR(20),
    suit VARCHAR(20),
    val INT(2),
    img VARCHAR(255),
    PRIMARY KEY (card, suit)
);

INSERT INTO deck (card, suit, val, img) VALUES
('Ace', 'Hearts', 11, 'https://raw.githubusercontent.com/YE-SPEN/bbhl-web-app/main/bbhl-app/src/assets/deck/ace_of_hearts.png'),
('Two', 'Hearts', 2, 'https://raw.githubusercontent.com/YE-SPEN/bbhl-web-app/main/bbhl-app/src/assets/deck/2_of_hearts.png'),
('Three', 'Hearts', 3, 'https://raw.githubusercontent.com/YE-SPEN/bbhl-web-app/main/bbhl-app/src/assets/deck/3_of_hearts.png'),
('Four', 'Hearts', 4, 'https://raw.githubusercontent.com/YE-SPEN/bbhl-web-app/main/bbhl-app/src/assets/deck/4_of_hearts.png'),
('Five', 'Hearts', 5, 'https://raw.githubusercontent.com/YE-SPEN/bbhl-web-app/main/bbhl-app/src/assets/deck/5_of_hearts.png'),
('Six', 'Hearts', 6, 'https://raw.githubusercontent.com/YE-SPEN/bbhl-web-app/main/bbhl-app/src/assets/deck/6_of_hearts.png'),
('Seven', 'Hearts', 7, 'https://raw.githubusercontent.com/YE-SPEN/bbhl-web-app/main/bbhl-app/src/assets/deck/7_of_hearts.png'),
('Eight', 'Hearts', 8, 'https://raw.githubusercontent.com/YE-SPEN/bbhl-web-app/main/bbhl-app/src/assets/deck/8_of_hearts.png'),
('Nine', 'Hearts', 9, 'https://raw.githubusercontent.com/YE-SPEN/bbhl-web-app/main/bbhl-app/src/assets/deck/9_of_hearts.png'),
('Ten', 'Hearts', 10, 'https://raw.githubusercontent.com/YE-SPEN/bbhl-web-app/main/bbhl-app/src/assets/deck/10_of_hearts.png'),
('Jack', 'Hearts', 10, 'https://raw.githubusercontent.com/YE-SPEN/bbhl-web-app/main/bbhl-app/src/assets/deck/jack_of_hearts2.png'),
('Queen', 'Hearts', 10, 'https://raw.githubusercontent.com/YE-SPEN/bbhl-web-app/main/bbhl-app/src/assets/deck/queen_of_hearts2.png'),
('King', 'Hearts', 10, 'https://raw.githubusercontent.com/YE-SPEN/bbhl-web-app/main/bbhl-app/src/assets/deck/king_of_hearts2.png'),
('Ace', 'Diamonds', 11, 'https://raw.githubusercontent.com/YE-SPEN/bbhl-web-app/main/bbhl-app/src/assets/deck/ace_of_diamonds.png'),
('Two', 'Diamonds', 2, 'https://raw.githubusercontent.com/YE-SPEN/bbhl-web-app/main/bbhl-app/src/assets/deck/2_of_diamonds.png'),
('Three', 'Diamonds', 3, 'https://raw.githubusercontent.com/YE-SPEN/bbhl-web-app/main/bbhl-app/src/assets/deck/3_of_diamonds.png'),
('Four', 'Diamonds', 4, 'https://raw.githubusercontent.com/YE-SPEN/bbhl-web-app/main/bbhl-app/src/assets/deck/4_of_diamonds.png'),
('Five', 'Diamonds', 5, 'https://raw.githubusercontent.com/YE-SPEN/bbhl-web-app/main/bbhl-app/src/assets/deck/5_of_diamonds.png'),
('Six', 'Diamonds', 6, 'https://raw.githubusercontent.com/YE-SPEN/bbhl-web-app/main/bbhl-app/src/assets/deck/6_of_diamonds.png'),
('Seven', 'Diamonds', 7, 'https://raw.githubusercontent.com/YE-SPEN/bbhl-web-app/main/bbhl-app/src/assets/deck/7_of_diamonds.png'),
('Eight', 'Diamonds', 8, 'https://raw.githubusercontent.com/YE-SPEN/bbhl-web-app/main/bbhl-app/src/assets/deck/8_of_diamonds.png'),
('Nine', 'Diamonds', 9, 'https://raw.githubusercontent.com/YE-SPEN/bbhl-web-app/main/bbhl-app/src/assets/deck/9_of_diamonds.png'),
('Ten', 'Diamonds', 10, 'https://raw.githubusercontent.com/YE-SPEN/bbhl-web-app/main/bbhl-app/src/assets/deck/10_of_diamonds.png'),
('Jack', 'Diamonds', 10, 'https://raw.githubusercontent.com/YE-SPEN/bbhl-web-app/main/bbhl-app/src/assets/deck/jack_of_diamonds2.png'),
('Queen', 'Diamonds', 10, 'https://raw.githubusercontent.com/YE-SPEN/bbhl-web-app/main/bbhl-app/src/assets/deck/queen_of_diamonds2.png'),
('King', 'Diamonds', 10, 'https://raw.githubusercontent.com/YE-SPEN/bbhl-web-app/main/bbhl-app/src/assets/deck/king_of_diamonds2.png'),
('Ace', 'Clubs', 11, 'https://raw.githubusercontent.com/YE-SPEN/bbhl-web-app/main/bbhl-app/src/assets/deck/ace_of_clubs.png'),
('Two', 'Clubs', 2, 'https://raw.githubusercontent.com/YE-SPEN/bbhl-web-app/main/bbhl-app/src/assets/deck/2_of_clubs.png'),
('Three', 'Clubs', 3, 'https://raw.githubusercontent.com/YE-SPEN/bbhl-web-app/main/bbhl-app/src/assets/deck/3_of_clubs.png'),
('Four', 'Clubs', 4, 'https://raw.githubusercontent.com/YE-SPEN/bbhl-web-app/main/bbhl-app/src/assets/deck/4_of_clubs.png'),
('Five', 'Clubs', 5, 'https://raw.githubusercontent.com/YE-SPEN/bbhl-web-app/main/bbhl-app/src/assets/deck/5_of_clubs.png'),
('Six', 'Clubs', 6, 'https://raw.githubusercontent.com/YE-SPEN/bbhl-web-app/main/bbhl-app/src/assets/deck/6_of_clubs.png'),
('Seven', 'Clubs', 7, 'https://raw.githubusercontent.com/YE-SPEN/bbhl-web-app/main/bbhl-app/src/assets/deck/7_of_clubs.png'),
('Eight', 'Clubs', 8, 'https://raw.githubusercontent.com/YE-SPEN/bbhl-web-app/main/bbhl-app/src/assets/deck/8_of_clubs.png'),
('Nine', 'Clubs', 9, 'https://raw.githubusercontent.com/YE-SPEN/bbhl-web-app/main/bbhl-app/src/assets/deck/9_of_clubs.png'),
('Ten', 'Clubs', 10, 'https://raw.githubusercontent.com/YE-SPEN/bbhl-web-app/main/bbhl-app/src/assets/deck/10_of_clubs.png'),
('Jack', 'Clubs', 10, 'https://raw.githubusercontent.com/YE-SPEN/bbhl-web-app/main/bbhl-app/src/assets/deck/jack_of_clubs2.png'),
('Queen', 'Clubs', 10, 'https://raw.githubusercontent.com/YE-SPEN/bbhl-web-app/main/bbhl-app/src/assets/deck/queen_of_clubs2.png'),
('King', 'Clubs', 10, 'https://raw.githubusercontent.com/YE-SPEN/bbhl-web-app/main/bbhl-app/src/assets/deck/king_of_clubs2.png'),
('Ace', 'Spades', 11, 'https://raw.githubusercontent.com/YE-SPEN/bbhl-web-app/main/bbhl-app/src/assets/deck/ace_of_spades.png'),
('Two', 'Spades', 2, 'https://raw.githubusercontent.com/YE-SPEN/bbhl-web-app/main/bbhl-app/src/assets/deck/2_of_spades.png'),
('Three', 'Spades', 3, 'https://raw.githubusercontent.com/YE-SPEN/bbhl-web-app/main/bbhl-app/src/assets/deck/3_of_spades.png'),
('Four', 'Spades', 4, 'https://raw.githubusercontent.com/YE-SPEN/bbhl-web-app/main/bbhl-app/src/assets/deck/4_of_spades.png'),
('Five', 'Spades', 5, 'https://raw.githubusercontent.com/YE-SPEN/bbhl-web-app/main/bbhl-app/src/assets/deck/5_of_spades.png'),
('Six', 'Spades', 6, 'https://raw.githubusercontent.com/YE-SPEN/bbhl-web-app/main/bbhl-app/src/assets/deck/6_of_spades.png'),
('Seven', 'Spades', 7, 'https://raw.githubusercontent.com/YE-SPEN/bbhl-web-app/main/bbhl-app/src/assets/deck/7_of_spades.png'),
('Eight', 'Spades', 8, 'https://raw.githubusercontent.com/YE-SPEN/bbhl-web-app/main/bbhl-app/src/assets/deck/8_of_spades.png'),
('Nine', 'Spades', 9, 'https://raw.githubusercontent.com/YE-SPEN/bbhl-web-app/main/bbhl-app/src/assets/deck/9_of_spades.png'),
('Ten', 'Spades', 10, 'https://raw.githubusercontent.com/YE-SPEN/bbhl-web-app/main/bbhl-app/src/assets/deck/10_of_spades.png'),
('Jack', 'Spades', 10, 'https://raw.githubusercontent.com/YE-SPEN/bbhl-web-app/main/bbhl-app/src/assets/deck/jack_of_spades2.png'),
('Queen', 'Spades', 10, 'https://raw.githubusercontent.com/YE-SPEN/bbhl-web-app/main/bbhl-app/src/assets/deck/queen_of_spades2.png'),
('King', 'Spades', 10, 'https://raw.githubusercontent.com/YE-SPEN/bbhl-web-app/main/bbhl-app/src/assets/deck/king_of_spades2.png')
