CREATE TABLE Players (
    id VARCHAR(90) PRIMARY KEY,
	name VARCHAR(90),
    position VARCHAR(30),
    year_joined INT(4)
);

INSERT INTO Players (id, name, position, year_joined) VALUES 
('tjward', 'TJ Ward', 'Forward', '2021'),
('andrewesdon', 'Andrew Esdon', 'Forward', '2021'),
('brandonrunnings', 'Brandon Runnings', 'Forward, Defenseman', '2021'),
('mattpatulli', 'Matt Patulli', 'Forward', '2021'),
('jasonquinn', 'Jason Quinn', 'Forward', '2021'),
('ryanlemay', 'Ryan Lemay', 'Forward', '2021'),
('ryanpatulli', 'Ryan Patulli', 'Defenseman', '2021'),
('andrewpalucci', 'Andrew Palucci', 'Forward', '2021'),
('davidsabini', 'David Sabini', 'Forward', '2022'),
('adamguillemette', 'Adam Guillemette', 'Forward', '2021'),
('ryangore', 'Ryan Gore', 'Forward, Defenseman', '2021'),
('geraldgodfrey', 'Gerald Godfrey', 'Forward', '2021'),
('isaacjenne', 'Isaac Jenne', 'Forward', '2021'),
('mathieusavoie', 'Mathieu Savoie', 'Forward', '2021'),
('shawnsproule', 'Shawn Sproule', 'Forward', '2021'),
('davidmontgomery', 'David Montgomery', 'Forward, Defenseman', '2021'),
('adammcsweeny', 'Adam McSweeny', 'Forward', '2021'),
('matttvaronas', 'Matt Tvaronas', 'Forward', '2021'),
('gregkelley', 'Greg Kelley', 'Forward, Defenseman', '2021'),
('trevordavies', 'Trevor Davies', 'Forward', '2021'),
('marcglaude', 'Marc Glaude', 'Defenseman', '2022'),
('evanmacrae', 'Evan Macrae', 'Forward', '2021'),
('thomasribeiro', 'Thomas Ribeiro', 'Forward, Defenseman', '2021'),
('gablovera', 'Gab Lovera', 'Defenseman', '2021'),
('kylerunnings', 'Kyle Runnings', 'Forward', '2021'),
('anthonygattuso', 'Anthony Gattuso', 'Forward', '2021'),
('andrewboyarchuk', 'Andrew Boyarchuk', 'Forward, Defenseman', '2021'),
('kevinflood', 'Kevin Flood', 'Defenseman', '2021'),
('bengodfrey', 'Ben Godfrey', 'Defenseman', '2021'),
('richardchurch', 'Richard Church', 'Forward', '2021'),
('shanepollard', 'Shane Pollard', 'Forward', '2021'),
('lucasscullion', 'Lucas Scullion', 'Forward, Defenseman', '2021'),
('jonathanpalucci', 'Jonathan Palucci', 'Forward', '2021'),
('stefanospinelli', 'Stefano Spinelli', 'Forward', '2021'),
('jasonstocker', 'Jason Stocker', 'Forward', '2021'),
('davidpidgeon', 'David Pidgeon', 'Forward', '2022'),
('chrisdelia', 'Chris D’Elia', 'Defenseman', '2021'),
('timoconnell', 'Tim O’Connell', 'Defenseman', '2021'),
('ryanhandfield', 'Ryan Handfield', 'Defenseman', '2021'),
('alexsimpson', 'Alex Simpson', 'Defenseman', '2021'),
('nickishak', 'Nick Ishak', 'Forward, Defenseman', '2021'),
('marcospinelli', 'Marco Spinelli', 'Forward, Defenseman', '2022'),
('danielandrzejewski', 'Daniel Andrzejewski', 'Forward', '2021'),
('philbarnes', 'Phil Barnes', 'Forward', '2021'),
('mattvirgini', 'Matt Virgini', 'Forward', '2021'),
('joerogers', 'Joe Rogers', 'Forward', '2021'),
('chrisbarnett', 'Chris Barnett', 'Forward', '2021'),
('johnpapaconstantinou', 'John Papaconstantinou', 'Forward', '2021'),
('tylerwatt', 'Tyler Watt', 'Defenseman', '2021'),
('ryansteger', 'Ryan Steger', 'Forward', '2021'),
('evananderson', 'Evan Anderson', 'Forward, Defenseman', '2021'),
('mattgriffiths', 'Matt Griffiths', 'Goalie', '2021'),
('marcbatty', 'Marc Batty', 'Defenseman', '2022'),
('scottcotroneo', 'Scott Cotroneo', 'Defenseman', '2022'),
('justinpugliese', 'Justin Pugliese', 'Forward', '2022'),
('mikepaolucci', 'Mike Paolucci', 'Forward', '2021'),
('justinromeo', 'Justin Romeo', 'Defenseman', '2021'),
('mikeviglas', 'Mike Viglas', 'Forward', '2021'),
('brandonmayoff', 'Brandon Mayoff', 'Forward, Defenseman', '2022'),
('ericspensieri', 'Eric Spensieri', 'Forward, Defenseman', '2021'),
('chrispalucci', 'Chris Palucci', 'Defenseman', '2021'),
('michaelboriero', 'Michael Boriero', 'Forward, Defenseman', '2021'),
('danielpatone', 'Daniel Patone', 'Defenseman', '2021'),
('michaelbrowne', 'Michael Browne', 'Forward', '2021'),
('davesabra', 'Dave Sabra', 'Forward', '2021'),
('christhorne', 'Chris Thorne', 'Defenseman', '2021'),
('robertobartolocio', 'Roberto Bartolocio', 'Forward', '2022'),
('spencersher', 'Spencer Sher', 'Forward', '2021'),
('michaelchabotar', 'Michael Chabotar', 'Forward, Defenseman', '2021'),
('alexlemay', 'Alex Lemay', 'Forward', '2021'),
('mikebatty', 'Mike Batty', 'Forward, Defenseman', '2021'),
('davidspiegel', 'David Spiegel', 'Forward', '2022'),
('jamiecollister', 'Jamie Collister', 'Defenseman, Goalie', '2021'),
('emotsiritas', 'Emo Tsiritas', 'Forward, Defenseman', '2022'),
('joncarlon', 'Jon Carlon', 'Defenseman', '2022'),
('anthonydimarco', 'Anthony Di Marco', 'Goalie', '2022'),
('robguttman', 'Rob Guttman', 'Forward, Defenseman', '2021'),
('jasonpolson', 'Jason Polson', 'Forward, Defenseman', '2021'),
('jeffhamilton', 'Jeff Hamilton', 'Defenseman', '2021'),
('mattshowers', 'Matt Showers', 'Forward', '2022'),
('anthonypaolucci', 'Anthony Paolucci', 'Forward, Defenseman', '2021'),
('benmumme', 'Ben Mumme', 'Forward', '2022'),
('philippedaoust', 'Philippe Daoust', 'Defenseman', '2022'),
('rorybertrand', 'Rory Bertrand', 'Forward', '2021'),
('jeffsteger', 'Jeff Steger', 'Defenseman', '2021'),
('mattfijal', 'Matt Fijal', 'Forward', '2021'),
('derekdelgrosso', 'Derek Del Grosso', 'Forward', '2021'),
('umarazam', 'Umar Azam', 'Defenseman', '2022'),
('sandroditrapani', 'Sandro Di Trapani', 'Defenseman', '2021'),
('mattgagnon', 'Matt Gagnon', 'Forward', '2021'),
('carmeloplaitis', 'Carmelo Plaitis', 'Defenseman', '2021'),
('nickmumme', 'Nick Mumme', 'Defenseman', '2021'),
('eddiepiazza', 'Eddie Piazza', 'Forward', '2021'),
('joshbazar', 'Josh Bazar', 'Forward', '2022'),
('evanmorris', 'Evan Morris', 'Goalie', '2022'),
('marcmajor', 'Marc Major', 'Goalie', '2021'),
('martinbeauchamp', 'Martin Beauchamp', 'Defenseman', '2021'),
('j-mmaurice', 'J-M Maurice', 'Forward', '2021'),
('louispapineau', 'Louis Papineau', 'Goalie', '2022'),
('bernardobellini', 'Bernardo Bellini', 'Goalie', '2021'),
('chrisratcheff', 'Chris Ratcheff', 'Goalie', '2021'),
('bradjohns', 'Brad Johns', 'Goalie', '2021'),
('mikelipkowitz', 'Mike Lipkowitz', 'Goalie', '2021'),
('seanmichaud', 'Sean Michaud', 'Forward', '2022'),
('loganbrett', 'Logan Brett', 'Defenseman', '2021'),
('ryandouglass', 'Ryan Douglass', 'Forward', '2021'),
('michaelnachaty', 'Michael Nachaty', 'Forward', '2022'),
('matianovale', 'Mat Ianovale', 'Forward', '2021'),
('johntodi', 'John Todi', 'Forward', '2021'),
('stevenfinlay', 'Steven Finlay', 'Defenseman', '2021'),
('danielrosenoff', 'Daniel Rosenoff', 'Forward', '2023'),
('chrisdomsodi', 'Chris Domsodi', 'Defenseman', '2021'),
('adamstrumas', 'Adam Strumas', 'Defenseman', '2021'),
('matthewbatty', 'Matthew Batty', 'Forward', '2023'),
('huntermoreau', 'Hunter Moreau', 'Forward', '2023'),
('seankerrick', 'Sean Kerrick', 'Forward', '2021'),
('miketvaronas', 'Mike Tvaronas', 'Forward', '2023'),
('kylearmstrong', 'Kyle Armstrong', 'Forward', '2021'),
('alexscodras', 'Alex Scodras', 'Forward', '2021'),
('stevenhrycko', 'Steven Hrycko', 'Defenseman', '2021'),
('dimitritsitouras', 'Dimitri Tsitouras', 'Forward', '2023'),
('jeffgray', 'Jeff Gray', 'Forward', '2023'),
('zackdoliveira', 'Zack D’Oliveira', 'Forward', '2023'),
('mikeknopp', 'Mike Knopp', 'Forward', '2023'),
('patmalette', 'Pat Malette', 'Defenseman', '2021'),
('kevinmulhern', 'Kevin Mulhern', 'Forward', '2023'),
('andrewanagnostopoulos', 'Andrew Anagnostopoulos', 'Forward', '2023'),
('thomasmann', 'Thomas Mann', 'Defenseman', '2021'),
('andrewkouyoumdijan', 'Andrew Kouyoumdijan', 'Forward', '2023'),
('erictrivisonno', 'Eric Trivisonno', 'Forward', '2023'),
('raymondkingsley', 'Raymond Kingsley', 'Forward', '2023'),
('jemmcdonald', 'Jem McDonald', 'Forward', '2023'),
('justingiglio', 'Justin Giglio', 'Forward', '2023'),
('mikezenobi', 'Mike Zenobi', 'Forward', '2021'),
('jamesdonald', 'James Donald', 'Forward, Defenseman', '2021'),
('ginogiliati', 'Gino Giliati', 'Forward', '2023'),
('grantgilead', 'Grant Gilead', 'Forward', '2023'),
('nickmagnan', 'Nick Magnan', 'Forward', '2021'),
('brianmarchetti', 'Brian Marchetti', 'Goalie', '2023'),
('aidenlondei', 'Aiden Londei', 'Forward', '2021'),
('nicholasmatte', 'Nicholas Matte', 'Forward', '2021'),
('zachzemokhol', 'Zach Zemokhol', 'Defenseman', '2021'),
('matthewlee', 'Matthew Lee', 'Defenseman', '2021'),
('matthewlondei', 'Matthew Londei', 'Defenseman', '2021'),
('johnvrettis', 'John Vrettis', 'Goalie', '2021')




