CREATE TABLE Players (
    id VARCHAR(90) PRIMARY KEY,
    name VARCHAR(90),
    position VARCHAR(30),
    player_rank DECIMAL(4,2),
    picture VARCHAR(255) DEFAULT 'https://cdn4.iconfinder.com/data/icons/small-n-flat/24/user-alt-512.png'
);

INSERT INTO Players (id, name, position, player_rank, picture) VALUES 
('adamguillemette', 'Adam Guillemette', 'Forward', 8.5, 'https://i0.wp.com/thebbhl.ca/wp-content/uploads/2016/09/GuillemetteAdam.png?resize=273%2C300&ssl=1'),
('adammcsweeny', 'Adam McSweeny', 'Forward', 7.5, 'https://i0.wp.com/thebbhl.ca/wp-content/uploads/2016/09/McSweenyAdam-e1476498982245.png?resize=252%2C300&ssl=1'),
('adamstrumas', 'Adam Strumas', 'Defenseman', 8.5, 'https://i0.wp.com/thebbhl.ca/wp-content/uploads/2018/09/Capture-1.png?resize=300%2C297&ssl=1'),
('aidenlondei', 'Aiden Londei', 'Forward', , 'https://cdn4.iconfinder.com/data/icons/small-n-flat/24/user-alt-512.png'),
('alexlemay', 'Alex Lemay', 'Forward', , 'https://cdn4.iconfinder.com/data/icons/small-n-flat/24/user-alt-512.png'),
('alexscodras', 'Alex Scodras', 'Forward', 7.5, 'https://cdn4.iconfinder.com/data/icons/small-n-flat/24/user-alt-512.png'),
('alexsimpson', 'Alex Simpson', 'Defenseman', 6, 'https://i0.wp.com/thebbhl.ca/wp-content/uploads/2016/09/SimpsonAlex.png?w=104&ssl=1'),
('andrewanagnostopoulos', 'Andrew Anagnostopoulos', 'Forward', 7.25, 'https://cdn4.iconfinder.com/data/icons/small-n-flat/24/user-alt-512.png'),
('andrewboyarchuk', 'Andrew Boyarchuk', 'Forward, Defenseman', 7.25, 'https://i0.wp.com/thebbhl.ca/wp-content/uploads/2016/09/BoyarchukAndrew.png?resize=300%2C288&ssl=1'),
('andrewesdon', 'Andrew Esdon', 'Forward', , 'https://cdn4.iconfinder.com/data/icons/small-n-flat/24/user-alt-512.png'),
('andrewkouyoumdijan', 'Andrew Kouyoumdijan', 'Forward', 6, 'https://cdn4.iconfinder.com/data/icons/small-n-flat/24/user-alt-512.png'),
('andrewpalucci', 'Andrew Palucci', 'Forward', 10, 'https://i0.wp.com/thebbhl.ca/wp-content/uploads/2016/09/PalucciAndrew.png?resize=191%2C300&ssl=1'),
('anthonydimarco', 'Anthony Di Marco', 'Goalie', , 'https://cdn4.iconfinder.com/data/icons/small-n-flat/24/user-alt-512.png'),
('anthonygattuso', 'Anthony Gattuso', 'Forward', 6.5, 'https://cdn4.iconfinder.com/data/icons/small-n-flat/24/user-alt-512.png'),
('anthonypaolucci', 'Anthony Paolucci', 'Forward, Defenseman', , 'https://cdn4.iconfinder.com/data/icons/small-n-flat/24/user-alt-512.png'),
('bengodfrey', 'Ben Godfrey', 'Defenseman', 10, 'https://i0.wp.com/thebbhl.ca/wp-content/uploads/2016/09/GodfreyBen.png?resize=145%2C300&ssl=1'),
('benmumme', 'Ben Mumme', 'Forward', , 'https://cdn4.iconfinder.com/data/icons/small-n-flat/24/user-alt-512.png'),
('bernardobellini', 'Bernardo Bellini', 'Goalie', 7, 'https://i0.wp.com/thebbhl.ca/wp-content/uploads/2016/09/BelliniBernardo.png?w=242&ssl=1'),
('bradjohns', 'Brad Johns', 'Goalie', 10, 'https://cdn4.iconfinder.com/data/icons/small-n-flat/24/user-alt-512.png'),
('brandonmayoff', 'Brandon Mayoff', 'Forward, Defenseman', , 'https://cdn4.iconfinder.com/data/icons/small-n-flat/24/user-alt-512.png'),
('brandonrunnings', 'Brandon Runnings', 'Forward, Defenseman', 8.5, 'https://i0.wp.com/thebbhl.ca/wp-content/uploads/2016/09/RunningsBrandon.png?resize=280%2C300&ssl=1'),
('brianmarchetti', 'Brian Marchetti', 'Goalie', 9, 'https://cdn4.iconfinder.com/data/icons/small-n-flat/24/user-alt-512.png'),
('brodyarmstrong', 'Brody Armstrong', 'Forward', 8.5, 'https://cdn4.iconfinder.com/data/icons/small-n-flat/24/user-alt-512.png'),
('carmeloplaitis', 'Carmelo Plaitis', 'Defenseman', , 'https://cdn4.iconfinder.com/data/icons/small-n-flat/24/user-alt-512.png'),
('charlesmigner', 'Charles Migner', 'Forward', 5, 'https://cdn4.iconfinder.com/data/icons/small-n-flat/24/user-alt-512.png'),
('chrisbarnett', 'Chris Barnett', 'Forward', 7, 'https://i0.wp.com/thebbhl.ca/wp-content/uploads/2016/09/BarnettChris.png?resize=153%2C300&ssl=1'),
('chrisdelia', 'Chris D’Elia', 'Defenseman', 10, 'https://i0.wp.com/thebbhl.ca/wp-content/uploads/2016/09/DeliaChris.png?w=229&ssl=1'),
('chrisdomsodi', 'Chris Domsodi', 'Defenseman', , 'https://cdn4.iconfinder.com/data/icons/small-n-flat/24/user-alt-512.png'),
('chrishandfield', 'Chris Handfield', 'Forward', 6, 'https://cdn4.iconfinder.com/data/icons/small-n-flat/24/user-alt-512.png'),
('chrispalucci', 'Chris Palucci', 'Defenseman', , 'https://cdn4.iconfinder.com/data/icons/small-n-flat/24/user-alt-512.png'),
('chrisratcheff', 'Chris Ratcheff', 'Goalie', 10, 'https://i0.wp.com/thebbhl.ca/wp-content/uploads/2016/10/RatcheffChris.png?resize=165%2C300&ssl=1'),
('christhorne', 'Chris Thorne', 'Defenseman', , 'https://cdn4.iconfinder.com/data/icons/small-n-flat/24/user-alt-512.png'),
('danielandrzejewski', 'Daniel Andrzejewski', 'Forward', , 'https://i0.wp.com/thebbhl.ca/wp-content/uploads/2016/09/AndrzejewskiDanny.png?w=151&ssl=1'),
('danielpatone', 'Daniel Patone', 'Defenseman', , 'https://cdn4.iconfinder.com/data/icons/small-n-flat/24/user-alt-512.png'),
('danielrosenoff', 'Daniel Rosenoff', 'Forward', , 'https://cdn4.iconfinder.com/data/icons/small-n-flat/24/user-alt-512.png'),
('daverania', 'Dave Rania', 'Forward', 7.5, 'https://cdn4.iconfinder.com/data/icons/small-n-flat/24/user-alt-512.png'),
('davesabra', 'Dave Sabra', 'Forward', 7, 'https://i0.wp.com/thebbhl.ca/wp-content/uploads/2016/09/SabraDave.png?resize=202%2C300&ssl=1'),
('davidmontgomery', 'David Montgomery', 'Forward, Defenseman', 8.5, 'https://i0.wp.com/thebbhl.ca/wp-content/uploads/2016/09/MontgomeryDavid.png?resize=300%2C152&ssl=1'),
('davidpidgeon', 'David Pidgeon', 'Forward', , 'https://cdn4.iconfinder.com/data/icons/small-n-flat/24/user-alt-512.png'),
('davidsabini', 'David Sabini', 'Forward', , 'https://cdn4.iconfinder.com/data/icons/small-n-flat/24/user-alt-512.png'),
('davidspiegel', 'David Spiegel', 'Forward', 6, 'https://i0.wp.com/thebbhl.ca/wp-content/uploads/1988/05/SpiegelDavid.png?w=181&ssl=1'),
('derekdelgrosso', 'Derek Del Grosso', 'Forward', 6.5, 'https://i0.wp.com/thebbhl.ca/wp-content/uploads/2016/09/DelGrossoDerek.png?resize=228%2C300&ssl=1'),
('dimitritsitouras', 'Dimitri Tsitouras', 'Forward', 7.5, 'https://cdn4.iconfinder.com/data/icons/small-n-flat/24/user-alt-512.png'),
('eddiepiazza', 'Eddie Piazza', 'Forward', 4.5, 'https://i0.wp.com/thebbhl.ca/wp-content/uploads/1983/11/Eddie.jpg?resize=300%2C200&ssl=1'),
('emotsiritas', 'Emo Tsiritas', 'Forward, Defenseman', , 'https://cdn4.iconfinder.com/data/icons/small-n-flat/24/user-alt-512.png'),
('ericspensieri', 'Eric Spensieri', 'Forward, Defenseman', , 'https://i0.wp.com/thebbhl.ca/wp-content/uploads/2017/10/Spen.jpg?resize=169%2C300&ssl=1'),
('erictrivisonno', 'Eric Trivisonno', 'Forward', 7.5, 'https://cdn4.iconfinder.com/data/icons/small-n-flat/24/user-alt-512.png'),
('evananderson', 'Evan Anderson', 'Forward, Defenseman', 5.5, 'https://i0.wp.com/thebbhl.ca/wp-content/uploads/2016/09/AndersonEvan.png?resize=165%2C300&ssl=1'),
('evanmacrae', 'Evan Macrae', 'Forward', , 'https://cdn4.iconfinder.com/data/icons/small-n-flat/24/user-alt-512.png'),
('evanmorris', 'Evan Morris', 'Goalie', , 'https://cdn4.iconfinder.com/data/icons/small-n-flat/24/user-alt-512.png'),
('gablovera', 'Gab Lovera', 'Defenseman', 7, 'https://i0.wp.com/thebbhl.ca/wp-content/uploads/2016/09/LoveraGab.jpg?resize=200%2C300&ssl=1'),
('geraldgodfrey', 'Gerald Godfrey', 'Forward', 9, 'https://i0.wp.com/thebbhl.ca/wp-content/uploads/2016/09/GodfreyGerald.png?resize=267%2C300&ssl=1'),
('ginogiliati', 'Gino Giliati', 'Forward', 4.5, 'https://cdn4.iconfinder.com/data/icons/small-n-flat/24/user-alt-512.png'),
('grantgilead', 'Grant Gilead', 'Forward', 5, 'https://cdn4.iconfinder.com/data/icons/small-n-flat/24/user-alt-512.png'),
('gregkelley', 'Greg Kelley', 'Forward, Defenseman', 6, 'https://i0.wp.com/thebbhl.ca/wp-content/uploads/2016/09/KelleyGreg.jpg?resize=225%2C300&ssl=1'),
('huntermoreau', 'Hunter Moreau', 'Forward', 9.5, 'https://cdn4.iconfinder.com/data/icons/small-n-flat/24/user-alt-512.png'),
('isaacjenne', 'Isaac Jenne', 'Forward', 8.5, 'https://i0.wp.com/thebbhl.ca/wp-content/uploads/2016/09/JenneIsaac.png?resize=238%2C300&ssl=1'),
('jamesdonald', 'James Donald', 'Forward, Defenseman', 5, 'https://i0.wp.com/thebbhl.ca/wp-content/uploads/2018/09/JD.jpg?w=316&ssl=1'),
('jamiecollister', 'Jamie Collister', 'Defenseman, Goalie', 6.5, 'https://i0.wp.com/thebbhl.ca/wp-content/uploads/2016/09/CollisterJamie.jpg?resize=200%2C300&ssl=1'),
('jasonpolson', 'Jason Polson', 'Forward, Defenseman', , 'https://cdn4.iconfinder.com/data/icons/small-n-flat/24/user-alt-512.png'),
('jasonquinn', 'Jason Quinn', 'Forward', 10, 'https://i0.wp.com/thebbhl.ca/wp-content/uploads/2016/09/quinn.jpeg?resize=300%2C300&ssl=1'),
('jasonstocker', 'Jason Stocker', 'Forward', , 'https://cdn4.iconfinder.com/data/icons/small-n-flat/24/user-alt-512.png'),
('jeffgray', 'Jeff Gray', 'Forward', 7, 'https://cdn4.iconfinder.com/data/icons/small-n-flat/24/user-alt-512.png'),
('jeffhamilton', 'Jeff Hamilton', 'Defenseman', , 'https://cdn4.iconfinder.com/data/icons/small-n-flat/24/user-alt-512.png'),
('jeffsteger', 'Jeff Steger', 'Defenseman', 6.25, 'https://cdn4.iconfinder.com/data/icons/small-n-flat/24/user-alt-512.png'),
('jemmcdonald', 'Jem McDonald', 'Forward', 4, 'https://cdn4.iconfinder.com/data/icons/small-n-flat/24/user-alt-512.png'),
('j-mmaurice', 'J-M Maurice', 'Forward', 5.5, 'https://i0.wp.com/thebbhl.ca/wp-content/uploads/2016/09/MauriceJ-M.jpg?resize=300%2C169&ssl=1'),
('joerogers', 'Joe Rogers', 'Forward', 5, 'https://i0.wp.com/thebbhl.ca/wp-content/uploads/2016/09/RogersJoe.png?resize=103%2C300&ssl=1'),
('joeydunne-fox', 'Joey Dunne-Fox', 'Forward', 8, 'https://cdn4.iconfinder.com/data/icons/small-n-flat/24/user-alt-512.png'),
('johnpapaconstantinou', 'John Papaconstantinou', 'Forward', 6.5, 'https://cdn4.iconfinder.com/data/icons/small-n-flat/24/user-alt-512.png'),
('johntodi', 'John Todi', 'Forward', 8, 'https://i0.wp.com/thebbhl.ca/wp-content/uploads/2019/09/John-Todi.jpg?resize=300%2C296&ssl=1'),
('johnvrettis', 'John Vrettis', 'Goalie', , 'https://cdn4.iconfinder.com/data/icons/small-n-flat/24/user-alt-512.png'),
('joncarlon', 'Jon Carlon', 'Defenseman', , 'https://cdn4.iconfinder.com/data/icons/small-n-flat/24/user-alt-512.png'),
('jonathanpalucci', 'Jonathan Palucci', 'Forward', 9.5, 'https://i0.wp.com/thebbhl.ca/wp-content/uploads/2016/09/PalucciJonny.jpg?resize=300%2C300&ssl=1'),
('joshbazar', 'Josh Bazar', 'Forward', , 'https://cdn4.iconfinder.com/data/icons/small-n-flat/24/user-alt-512.png'),
('justingiglio', 'Justin Giglio', 'Forward', 4, 'https://cdn4.iconfinder.com/data/icons/small-n-flat/24/user-alt-512.png'),
('justinpugliese', 'Justin Pugliese', 'Forward', , 'https://cdn4.iconfinder.com/data/icons/small-n-flat/24/user-alt-512.png'),
('justinromeo', 'Justin Romeo', 'Defenseman', , 'https://i0.wp.com/thebbhl.ca/wp-content/uploads/2016/09/Romeo.jpg?resize=169%2C300&ssl=1'),
('justinsadowy', 'Justin Sadowy', 'Forward', 7.25, 'https://cdn4.iconfinder.com/data/icons/small-n-flat/24/user-alt-512.png'),
('kevinflood', 'Kevin Flood', 'Defenseman', 7.5, 'https://i0.wp.com/thebbhl.ca/wp-content/uploads/2016/09/FloodKevin.jpg?resize=300%2C200&ssl=1'),
('kevinmulhern', 'Kevin Mulhern', 'Forward', 8, 'https://cdn4.iconfinder.com/data/icons/small-n-flat/24/user-alt-512.png'),
('kylearmstrong', 'Kyle Armstrong', 'Forward', 10, 'https://cdn4.iconfinder.com/data/icons/small-n-flat/24/user-alt-512.png'),
('kylerunnings', 'Kyle Runnings', 'Forward', 7.25, 'https://i0.wp.com/thebbhl.ca/wp-content/uploads/2016/09/RunningsKyle.jpg?resize=300%2C300&ssl=1'),
('loganbrett', 'Logan Brett', 'Defenseman', 6.5, 'https://i0.wp.com/thebbhl.ca/wp-content/uploads/2016/09/Logan.png?resize=300%2C200&ssl=1'),
('louispapineau', 'Louis Papineau', 'Goalie', , 'https://cdn4.iconfinder.com/data/icons/small-n-flat/24/user-alt-512.png'),
('lucasscullion', 'Lucas Scullion', 'Forward, Defenseman', , 'https://i0.wp.com/thebbhl.ca/wp-content/uploads/2016/09/ScullionLucas.jpg?resize=169%2C300&ssl=1'),
('marcbatty', 'Marc Batty', 'Defenseman', , 'https://cdn4.iconfinder.com/data/icons/small-n-flat/24/user-alt-512.png'),
('marcglaude', 'Marc Glaude', 'Defenseman', , 'https://cdn4.iconfinder.com/data/icons/small-n-flat/24/user-alt-512.png'),
('marcmajor', 'Marc Major', 'Goalie', 6.5, 'https://i0.wp.com/thebbhl.ca/wp-content/uploads/2016/10/Major.png?w=181&ssl=1'),
('marcospinelli', 'Marco Spinelli', 'Forward, Defenseman', , 'https://cdn4.iconfinder.com/data/icons/small-n-flat/24/user-alt-512.png'),
('martinbeauchamp', 'Martin Beauchamp', 'Defenseman', 7, 'https://i0.wp.com/thebbhl.ca/wp-content/uploads/2016/09/BeauchampsMartin.jpg?resize=169%2C300&ssl=1'),
('mathieusavoie', 'Mathieu Savoie', 'Forward', 9, 'https://cdn4.iconfinder.com/data/icons/small-n-flat/24/user-alt-512.png'),
('mattfijal', 'Matt Fijal', 'Forward', , 'https://cdn4.iconfinder.com/data/icons/small-n-flat/24/user-alt-512.png'),
('mattgagnon', 'Matt Gagnon', 'Forward', 5, 'https://i0.wp.com/thebbhl.ca/wp-content/uploads/2016/09/GagnonMatt.png?w=223&ssl=1'),
('mattgriffiths', 'Matt Griffiths', 'Goalie', 6.5, 'https://cdn4.iconfinder.com/data/icons/small-n-flat/24/user-alt-512.png'),
('mattpatulli', 'Matt Patulli', 'Forward', 9.5, 'https://i0.wp.com/thebbhl.ca/wp-content/uploads/2016/10/PatulliMatt.jpg?resize=300%2C300&ssl=1'),
('mattshowers', 'Matt Showers', 'Forward', , 'https://cdn4.iconfinder.com/data/icons/small-n-flat/24/user-alt-512.png'),
('matttvaronas', 'Matt Tvaronas', 'Forward', 9, 'https://cdn4.iconfinder.com/data/icons/small-n-flat/24/user-alt-512.png'),
('mattvirgini', 'Matt Virgini', 'Forward', 5.5, 'https://i0.wp.com/thebbhl.ca/wp-content/uploads/2016/09/VirginiMatt.png?resize=183%2C300&ssl=1'),
('matthewbatty', 'Matthew Batty', 'Forward', 9.5, 'https://i0.wp.com/thebbhl.ca/wp-content/uploads/2016/09/BattyMatt.jpg?resize=225%2C300&ssl=1'),
('matianovale', 'Matthew Ianovale', 'Forward', 9.5, 'https://cdn4.iconfinder.com/data/icons/small-n-flat/24/user-alt-512.png'),
('matthewlee', 'Matthew Lee', 'Defenseman', , 'https://cdn4.iconfinder.com/data/icons/small-n-flat/24/user-alt-512.png'),
('matthewlondei', 'Matthew Londei', 'Defenseman', , 'https://cdn4.iconfinder.com/data/icons/small-n-flat/24/user-alt-512.png'),
('michaelchabotar', 'Michael “Rico” Chabotar', 'Forward, Defenseman', 6.5, 'https://i0.wp.com/thebbhl.ca/wp-content/uploads/2016/09/ChabotarMichael.jpg?resize=300%2C300&ssl=1'),
('michaelboriero', 'Michael Boriero', 'Forward, Defenseman', 8, 'https://i0.wp.com/thebbhl.ca/wp-content/uploads/2016/09/BorieroMichael.png?resize=179%2C300&ssl=1'),
('michaelbrowne', 'Michael Browne', 'Forward', 7.5, 'https://i0.wp.com/thebbhl.ca/wp-content/uploads/2016/09/BrowneMike.jpg?resize=300%2C300&ssl=1'),
('michaelnachaty', 'Michael Nachaty', 'Forward', , 'https://cdn4.iconfinder.com/data/icons/small-n-flat/24/user-alt-512.png'),
('mikebatty', 'Mike Batty', 'Forward, Defenseman', 7, 'https://i0.wp.com/thebbhl.ca/wp-content/uploads/2016/09/BattyMike.jpg?resize=225%2C300&ssl=1'),
('mikeknopp', 'Mike Knopp', 'Forward', 8.5, 'https://cdn4.iconfinder.com/data/icons/small-n-flat/24/user-alt-512.png'),
('mikelipkowitz', 'Mike Lipkowitz', 'Defensemen', 4.5, 'https://i0.wp.com/thebbhl.ca/wp-content/uploads/2016/09/LipkowitzMike.png?resize=154%2C300&ssl=1'),
('mikepaolucci', 'Mike Paolucci', 'Forward', 6, 'https://i0.wp.com/thebbhl.ca/wp-content/uploads/2017/10/MP.jpg?resize=300%2C300&ssl=1'),
('mikepoole', 'Mike Poole', 'Forward', 7.25, 'https://cdn4.iconfinder.com/data/icons/small-n-flat/24/user-alt-512.png'),
('miketvaronas', 'Mike Tvaronas', 'Forward', 8.5, 'https://cdn4.iconfinder.com/data/icons/small-n-flat/24/user-alt-512.png'),
('mikeviglas', 'Mike Viglas', 'Forward', , 'https://cdn4.iconfinder.com/data/icons/small-n-flat/24/user-alt-512.png'),
('mikezenobi', 'Mike Zenobi', 'Forward', 6.25, 'https://cdn4.iconfinder.com/data/icons/small-n-flat/24/user-alt-512.png'),
('nicmagnan', 'Nic Magnan', 'Forward', 10, 'https://cdn4.iconfinder.com/data/icons/small-n-flat/24/user-alt-512.png'),
('nicholasmatte', 'Nicholas Matte', 'Forward', , 'https://cdn4.iconfinder.com/data/icons/small-n-flat/24/user-alt-512.png'),
('nickishak', 'Nick Ishak', 'Forward, Defenseman', 8, 'https://i0.wp.com/thebbhl.ca/wp-content/uploads/2016/09/IshakNick.jpg?resize=300%2C298&ssl=1'),
('nickmumme', 'Nick Mumme', 'Defenseman', 5.5, 'https://i0.wp.com/thebbhl.ca/wp-content/uploads/2016/09/MummeNick.png?resize=300%2C215&ssl=1'),
('nicksimatos', 'Nick Simatos', 'Forward', , 'https://cdn4.iconfinder.com/data/icons/small-n-flat/24/user-alt-512.png'),
('patmalette', 'Pat Malette', 'Defenseman', 7, 'https://cdn4.iconfinder.com/data/icons/small-n-flat/24/user-alt-512.png'),
('philbarnes', 'Phil Barnes', 'Forward', 7, 'https://i0.wp.com/thebbhl.ca/wp-content/uploads/2016/09/BarnesPhil.jpg?resize=300%2C300&ssl=1'),
('philippedaoust', 'Philippe Daoust', 'Defenseman', 6.25, 'https://cdn4.iconfinder.com/data/icons/small-n-flat/24/user-alt-512.png'),
('raymondkingsley', 'Raymond Kingsley', 'Forward', 4.5, 'https://cdn4.iconfinder.com/data/icons/small-n-flat/24/user-alt-512.png'),
('richardchurch', 'Richard Church', 'Forward', , 'https://cdn4.iconfinder.com/data/icons/small-n-flat/24/user-alt-512.png'),
('robguttman', 'Rob Guttman', 'Forward, Defenseman', 4.5, 'https://cdn4.iconfinder.com/data/icons/small-n-flat/24/user-alt-512.png'),
('robertobartolocio', 'Roberto Bartolocio', 'Forward', , 'https://cdn4.iconfinder.com/data/icons/small-n-flat/24/user-alt-512.png'),
('rorybertrand', 'Rory Bertrand', 'Forward', , 'https://cdn4.iconfinder.com/data/icons/small-n-flat/24/user-alt-512.png'),
('ryandouglass', 'Ryan Douglass', 'Forward', 6, 'https://i0.wp.com/thebbhl.ca/wp-content/uploads/2016/09/DouglassRyan.png?w=215&ssl=1'),
('ryangore', 'Ryan Gore', 'Forward, Defenseman', 10, 'https://i0.wp.com/thebbhl.ca/wp-content/uploads/2016/09/gore.jpg?resize=255%2C300&ssl=1'),
('ryanhandfield', 'Ryan Handfield', 'Defenseman', , 'https://i0.wp.com/thebbhl.ca/wp-content/uploads/2016/09/HandfieldRyan.png?w=97&ssl=1'),
('ryanlemay', 'Ryan Lemay', 'Forward', , 'https://cdn4.iconfinder.com/data/icons/small-n-flat/24/user-alt-512.png'),
('ryanpatulli', 'Ryan Patulli', 'Defenseman', 10, 'https://i0.wp.com/thebbhl.ca/wp-content/uploads/2016/09/PatulliRyan.jpg?resize=300%2C300&ssl=1'),
('ryansteger', 'Ryan Steger', 'Forward', 5.5, 'https://i0.wp.com/thebbhl.ca/wp-content/uploads/2016/09/StegerRyan.jpg?resize=264%2C300&ssl=1'),
('sandroditrapani', 'Sandro Di Trapani', 'Defenseman', 4.5, 'https://i0.wp.com/thebbhl.ca/wp-content/uploads/2016/09/DiTrapaniSandro.png?resize=230%2C300&ssl=1'),
('scottcotroneo', 'Scott Cotroneo', 'Defenseman', , 'https://cdn4.iconfinder.com/data/icons/small-n-flat/24/user-alt-512.png'),
('seankerrick', 'Sean Kerrick', 'Forward', 7.5, 'https://i0.wp.com/thebbhl.ca/wp-content/uploads/2019/09/kerrick.jpg?resize=240%2C300&ssl=1'),
('seanmichaud', 'Sean Michaud', 'Forward', , 'https://cdn4.iconfinder.com/data/icons/small-n-flat/24/user-alt-512.png'),
('shanepollard', 'Shane Pollard', 'Forward', 6.5, 'https://i0.wp.com/thebbhl.ca/wp-content/uploads/2016/09/PollardShane.jpg?resize=248%2C300&ssl=1'),
('shawnsproule', 'Shawn Sproule', 'Forward', 8, 'https://i0.wp.com/thebbhl.ca/wp-content/uploads/2016/09/SprouleShawn.png?resize=167%2C300&ssl=1'),
('spencersher', 'Spencer Sher', 'Forward', 6.25, 'https://i0.wp.com/thebbhl.ca/wp-content/uploads/2016/09/SherSpencer.png?resize=265%2C300&ssl=1'),
('stefanospinelli', 'Stefano Spinelli', 'Forward', , 'https://cdn4.iconfinder.com/data/icons/small-n-flat/24/user-alt-512.png'),
('stevenfinlay', 'Steven Finlay', 'Defenseman', , 'https://cdn4.iconfinder.com/data/icons/small-n-flat/24/user-alt-512.png'),
('stevenhrycko', 'Steven Hrycko', 'Defenseman', 8, 'https://cdn4.iconfinder.com/data/icons/small-n-flat/24/user-alt-512.png'),
('thomasmann', 'Thomas Mann', 'Defenseman', 7.25, 'https://cdn4.iconfinder.com/data/icons/small-n-flat/24/user-alt-512.png'),
('thomasribeiro', 'Thomas Ribeiro', 'Forward, Defenseman', 8, 'https://cdn4.iconfinder.com/data/icons/small-n-flat/24/user-alt-512.png'),
('timoconnell', 'Tim O’Connell', 'Defenseman', , 'https://cdn4.iconfinder.com/data/icons/small-n-flat/24/user-alt-512.png'),
('tjward', 'TJ Ward', 'Forward', 10, 'https://i0.wp.com/thebbhl.ca/wp-content/uploads/2016/09/ward.png?resize=166%2C300&ssl=1'),
('trevordavies', 'Trevor Davies', 'Forward', , 'https://cdn4.iconfinder.com/data/icons/small-n-flat/24/user-alt-512.png'),
('tylerwatt', 'Tyler Watt', 'Defenseman', , 'https://i0.wp.com/thebbhl.ca/wp-content/uploads/2016/09/ty.jpg?resize=171%2C300&ssl=1'),
('umarazam', 'Umar Azam', 'Defenseman', , 'https://cdn4.iconfinder.com/data/icons/small-n-flat/24/user-alt-512.png'),
('zackdoliveira', 'Zack D’Oliveira', 'Forward', 7, 'https://cdn4.iconfinder.com/data/icons/small-n-flat/24/user-alt-512.png'),
('zackzemokhol', 'Zack Zemokhol', 'Defenseman', , 'https://cdn4.iconfinder.com/data/icons/small-n-flat/24/user-alt-512.png')







